baseURL: "https://hicsuntdracones.me/"
title: ErC's Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ErC's Blog
  description: "ErC's personal blog"
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js

  label:
    text: "Home"
    icon: media/img/calcifer-cropped.jpg
    iconHeight: 50

  # home-info mode
  homeInfoParams:
    Title: "ErC's Blog"
    Content: "Welcome to my little corner. Here you'll find info about me and ways to contact me, but also my thoughts about cryptocurrencies, technology, politics and more. Beware: Hic Sunt Dracones."
  socialIcons:
    - name: github
      url: "https://github.com/erciccione"
    - name: mastodon
      url: "https://infosec.exchange/@erc"
    - name: twitter
      url: "https://twitter.com/calciferciccio"
    - name: reddit
      url: "https://reddit.com/u/erciccione"
    - name: pgpkey
      url: "pgp.txt"
    - name: email
      url: "/about"
    - name: matrix
      url: "https://matrix.to/#/@erc:cryptoriot.org"
    - name: rss
      url: "/blog/index.xml"

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true